version: "3.8"
services:
  db:
    image: postgres:15
    container_name: spring-batch_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: batch_db
    ports:
      - "5432:5432"
    restart: no
    volumes: # 修正済み
      - db_data:/var/lib/postgresql/data
    healthcheck: # データベースのヘルスチェック
      test: ["CMD-SHELL", "pg_isready -U user -d batch_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_batch_app
    depends_on:
      db:
        condition: service_healthy # db がヘルシーになるまで待つ
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/batch_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: no
volumes:
  db_data:
